language: go

go:
  - tip

services:
  - redis-server

script:
  - mkdir -p $GOPATH/src/gopkg.in/gilmour-libs/gilmour-e-go.v4
  - ls -s $(pwd)/backends $GOPATH/src/gopkg.in/gilmour-libs/gilmour-e-go.v4/backends
  - ls -s $(pwd)/ui $GOPATH/src/gopkg.in/gilmour-libs/gilmour-e-go.v4/ui
  - go test -v --race ./...
  - go build -v --race ./...

notifications:
  email:
    - piyush@piyushverma.net
